### ISSUE TITLE
Capture Framerate always 60 fps

### ISSUE THREAD

**Issue by cg-ite** [Kinovea/Kinovea#120]
Hi Joan,

I have a Razor RipsawX USB3 video-grabber, which gets recognised with all its resolution settings. But if I change the setting for the frame-rate i.e. to 30 or 50 fps, the final video-recoding is always 60 fps. Is that on purpose or is it a bug? 

If it's a bug, it's located in  https://github.com/Kinovea/Kinovea/blob/9d5a52ec44418034ff7a562dbfe27a06e1da12cf/Kinovea.Camera.DirectShow/FrameGrabber.cs#L117 
AverageFrameRate is always 60, no matter what fps is selected. A fix would be to remove this line an add ```resultingFramerate = info.SelectedFramerate;``` before line https://github.com/Kinovea/Kinovea/blob/9d5a52ec44418034ff7a562dbfe27a06e1da12cf/Kinovea.Camera.DirectShow/FrameGrabber.cs#L209

Should I send you a PR?

Greetings,
Christian

**Comment by JoanCharmant** [comment]
Thanks! I was able to reproduce this with an HDMI capture stick as well. I fixed it slightly differently but your root cause analysis helped very much.
