### ISSUE TITLE
Cameras Not Showing Up

### ISSUE THREAD

**Issue by lsmith24** [Kinovea/Kinovea#121]
Hi, 
I am using high speed cameras from Daheng and Basler. When running Kinovea from the executable download the cameras show up just fine, but when running from the source code they do not show up in the list of cameras to select from. The plugins are in the correct folder and if I step through the code it says the plugins were loaded correctly. They just don't seem to be discovered for some reason. Any thoughts on why this might be?

**Comment by JoanCharmant** [comment]
Set a breakpoint in CameraTypeManager.cs > `CheckCameras()`. 

Note that in the source version this will be called only if you have the camera tab visible in the UI, in the 0.9.5 version this was called constantly as an optimization but this was sometimes causing issues for people that don't even use cameras so I think it's best to only run it when the tab is visible. 

When you are in this function, check the value of `cameraManagers`, does it have the type of cameras you are expecting?  By default without any camera plugin installed it will have 3, DirectShow, IP camera and Camera Simulator. You should have more.

**Comment by lsmith24** [comment]
Thanks for your response!
It only shows the 3 camera types. When I step through further it seems like it might be catching an error in AddCameraManager() as it prints "Exception thrown: 'System.IO.FileNotFoundException' in Kinovea.Camera.dll" in that function. It seems like some dependency is missing but I'm not sure what that would be. The plugins for the cameras are in the folder that the help menu option brings me to (as the directions for the plugins say to do). Any help is appreciated.
Thank you!

**Comment by JoanCharmant** [comment]
I haven't worked on the Basler plugin for a while, it's probable the new version of Basler Pylon has a different native DLL that no longer matches and so the C# wrapper dll isn't finding what it expects.

**Comment by lsmith24** [comment]
Ah ok thank you. Do you know if there is a way that I can set up the camera plugin code to be debugged? It says the symbols aren't loaded so I cannot put break points in the Daheng and Basler specific camera manager functions.

**Comment by JoanCharmant** [comment]
In the camera type project, (ex: Kinovea.Camera.Daheng), on the build tab, set the output directory to be the matching plugin directory in AppData\Roaming\Kinovea\Plugins. This should make the main program use that version of the assembly.

**Comment by JoanCharmant** [comment]
As of now the last compatible version of Basler Pylon is 6.1. They since discontinued the PylonC wrapper assembly so there is some conversion work to be done to use Pylon 7.x

**Comment by lsmith24** [comment]
I actually am using version 6 I believe, but neither camera brand seems to be working. Will do some more investigating, appreciate the help though!

**Comment by JoanCharmant** [comment]
I have updated the plugin for Daheng Imaging. I think the main dependency issue was with log4net as this was updated.
 
The new plugins should work with Daheng Galaxy SDK/Runtime version 1.14.2305.8151 and superior, including latest versions from their website at this point, 1.24.2308.9101 and 2.0.2309.9252.

**Comment by JoanCharmant** [comment]
I'm going to close this issue. The newer plugins should work. There is also a new GenICam plugin in the code base that should work with all GenICam camera (may require some code changes for newer vendors), please try with this if the issue persist as it's likely to replace the vendor-specific plugins at some point.
