### ISSUE TITLE
How did you implement the auto tracking feature?

### ISSUE THREAD

**Issue by zhuolisam** [Kinovea/Kinovea#131]
Hi, great project. I have one question regarding the box tracker feature, that auto-tracks a high-contrast object, within a search window. How were you able to implement this feature? Please enlighten me.

**Comment by JoanCharmant** [comment]
Using OpenCV template matching. See `matchTemplate` function. https://docs.opencv.org/3.4/d4/dc6/tutorial_py_template_matching.html

**Comment by zhuolisam** [comment]
What about the three-point angle marker? I noticed that it can auto-track too. Is it using the same algorithm?

**Comment by JoanCharmant** [comment]
Yes, it does template matching for each point.

**Comment by zhuolisam** [comment]
I see, thanks!

**Comment by zhuolisam** [comment]
Hi @JoanCharmant .  I guess I will serve this thread as my question to you, since I'm not an expert in C# and I'm in the progress mimicking the implementation in Python. Can I ask how did you calculate the center of mass point based on the other key points of the human model? I do see there is a Human model.xml but I'm not sure where is the code for the algorithm.

**Comment by zhuolisam** [comment]
@JoanCharmant Hey Joan, bumping this thread again.

**Comment by JoanCharmant** [comment]
The center of mass is based on the weighted average of the different segments. The weight assigned to each segment is based on standard biometric tables from the literature, so using average values. The values are in the human model tool. The table used was passed to me by a biomechanics researcher by email but I don't have the exact source anymore. If needed we can restart from a source model and better document this.
