### ISSUE TITLE
[Bug] Calibration plane width/height in 2023.2

### ISSUE THREAD

**Issue by cg-ite** [Kinovea/Kinovea#143]
Hi Joan,
i'm testing the new calibration plane of version 2023.2 with some old kva-files. There is a bug if the width or the height of the plane is above 1000. In one of my kva file the width is 1000 cm for example. The two spin controls of the FormCalibratePlane have a maximum of 999 each, which leads to a `ArgumentOutOfRangeException` (Kinovea\Kinovea.ScreenManager\PlayerScreen\Forms\FormCalibratePlane.cs: row 92) . 
Is there a reason for the limitation of the width and height?

Greetings,
Chris

**Comment by JoanCharmant** [comment]
Thank you.
This should be fixed in master now. 

There is no reason to the maximum but the controls needs to have some sort of maximum so I set it to 1 million. Also added a check to avoid the exception if it's higher than that (at that point it's better to use a more appropriate unit).
