### ISSUE TITLE
ODF export (partially) broken

### ISSUE THREAD

**Issue by mado89** [Kinovea/Kinovea#3]
[Files.zip](https://github.com/Kinovea/Kinovea/files/3977732/Files.zip)
Hi,

to me it seems that the ODF export has a problem (in 0.8.27). When exporting data to a table the labels of the markers are not exported. Exporting the same file as xml or text works. 
I have attached the a sample (as txt, ods and xml).
I noticed that this seems to be noticable ony when opening the file using Microsoft Excel (2019, 1902) when opening it with Libre Office Calc (6.2.8.2).
Maybe it is due to a faulty library?

Thanks

**Comment by mado89** [comment]
Please let me know if you need more information to reproduce this issue.
I have not tested whether any other tools reading the file are affected by this.

**Comment by JoanCharmant** [comment]
I can open the file and it reads correctly in LibreOffice and in Google docs spreadsheets. I don't have Excel to check but it looks like it would be an issue in Excel support of ODF. For Excel you should use the XML export. You can also use the CSV export from menu Tools > Linear kinematics.
