### ISSUE TITLE
[Question / feature request] Is it possible to have a main HD output window in real-time?

### ISSUE THREAD

**Issue by Mitra-M** [Kinovea/Kinovea#4]
Hi ,
 Thanks for this great project.

Can we have a real-time HD output window instead of saving output to a video file?
I want to display the output as live on the second monitor.

**Comment by JoanCharmant** [comment]
Can you clarify what you mean please?

**Comment by JoanCharmant** [comment]
You should be able to share your main screen on the second monitor or use OBS to stream it on the local network.
