### ISSUE TITLE
Kinova.Video.FFMpeg - incomatible error

### ISSUE THREAD

**Issue by 001simonp** [Kinovea/Kinovea#8]
Attempted to load specific solution file PlayerServer.sln to upgrade - but files missing ?

PlayerServer\PlayerServer.vcproj: File '....\Downloads\Kinovea-master\Kinovea-master\Kinovea.Video.FFMpeg\PlayerServer\PlayerServer.vcproj' was not found.
--

**Comment by JoanCharmant** [comment]
Use the main solution, it imports the Kinovea.Video.FFMpeg project. No need to use a separate solution.
