### ISSUE TITLE
[Feature request] - for more control over the line measure tool, better undo

### ISSUE THREAD

**Issue by astandarduser** [Kinovea/Kinovea#81]
It would be great to have the ability to rotate a line without changing the distance by grabbing end points. Would also be great if end or middle points can be locked, and lock the length so the end point can be pivoted around the other end point or middle. Also the Undo completely deletes the line rather than the last change to the line

**Comment by JoanCharmant** [comment]
This kind of control is possible if you are creating your own drawing. Check the `Bike fit` tool and in its context menu use Options > Lock segment lengths. I mention this because the line is just two points so your comment about locking the middle point makes me think you are looking for something more complex than the simple line segment.

Yeah at the moment changes in position aren't added to the undo history, this absolutely needs to be fixed.

**Comment by astandarduser** [comment]
Thank you will give that a try, I only just found this software after looking for a tool to quickly annotate and get rough proportion on images to help with my 3d art. I tried every measuring tool I could find but if you know a better suited software for this then I'd love to know. The ability to set a line as a fixed length and for everything to dynamically change dependent on that line is what has me really liking Kinovea. Have a few ideas on features that would be amazing if they aren't already part of the software

-	Point to point snapping with the line tool

-	Quick grid over the entire image in 1 unit of whatever the chosen unit is of the initial line, and the ability to set it to something like 5 by 10 units so it’s rectangular

-	Select the line and bring up a general transform/rotate/scale box similar to photoshop with a shortcut

-	A ruler like tool with evenly distributed lines that can show units too and the amount of segments can be adjusted

**Comment by JoanCharmant** [comment]
Hi, 
For the grid/ruler I think the closest to this will be to show the coordinate system.

Try this:
- Locate the perspective grid tool button in the toolbar, right click it to bring the extra tools and choose the Grid.
- Add a grid object in the video.
- Right click the grid and choose "Calibrate". Enter values in whatever units.
- Go to the main menu Tools > Coordinate system.

For photo export you can right clicking and do Save image.

**Comment by astandarduser** [comment]
Thanks, just tried the grid option and it is good for calibration, my only suggestion for improvement would be to add an options menu for the coordinate system to change the grid to 10 by 10 , or 10 by 5 etc... More customization. The line tool alone is the easiest to use of any of the software I tried, with easy to read labels

**Comment by JoanCharmant** [comment]
Now that undo/redo of drawing move and resize was added in 2023.1 and separate controls for rows and columns were added in 2024.1, I'm going to close this issue as most of the points are addressed in one way or another. Please open new dedicated issues for any specifics. Thanks!
