### ISSUE TITLE
Non-ASCII characters cause build errors.

### ISSUE THREAD

**Issue by athletefirst** [Kinovea/Kinovea#97]
The following file contains non-ascii characters, which will cause build errors in Japanese VS2019:

- LanguageManager.cs
- ThumbnailFile.cs

Could you change these file encoding to UTF-8 with BOM.

Pull request ( #94 ) closed.

**Comment by JoanCharmant** [comment]
LanguageManager.cs is already saved as UTF-8 with BOM.

Can you go to VS options > Text editor > Auto detect UTF-8 encoding without signature. Does that help? This should be checked by default but maybe it got unchecked for you.

**Comment by athletefirst** [comment]
I checked the box, but could not open it.

It does not start with the byte order mark. So, it appears that it is not saved as UTF-8 with BOM.

![image](https://user-images.githubusercontent.com/79192861/195119407-27ee8e7b-e095-40b8-966d-52fc59dc45bc.png)

**Comment by JoanCharmant** [comment]
You mentioned LanguageManager.cs in the original post so that's the one I checked.

Can you confirm that if you save this one as UTF-8 with BOM it fixes the issue or are there other issues?

**Comment by athletefirst** [comment]
Yes, it will fixes my issue.

I'm sorry. I made a mistake.
The following two files:
- ScreenManager.cs
- ThumbnailFile.cs

**Comment by athletefirst** [comment]
New pull request, #99
